name: CI

on:
  workflow_dispatch:

# on:
#   push:
#     branches: [main]
#   pull_request:

jobs:
  php:
    name: PHP (${{ matrix.php-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: PHPCS
        run: composer lint

      - name: PHPStan
        run: composer phpstan

  js:
    name: JS & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint JS
        run: npm run lint:js

      - name: Lint CSS
        run: npm run lint:css

      - name: Build
        run: npm run build
